//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW10_DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GenderTable> GenderTable { get; set; }
        public virtual DbSet<OrdersTable> OrdersTable { get; set; }
        public virtual DbSet<PetsTable> PetsTable { get; set; }
        public virtual DbSet<RoleTable> RoleTable { get; set; }
        public virtual DbSet<ServicesTable> ServicesTable { get; set; }
        public virtual DbSet<TimeTable> TimeTable { get; set; }
        public virtual DbSet<UserPhoto> UserPhoto { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WorkersTable> WorkersTable { get; set; }
        public virtual DbSet<WorkTimeTable> WorkTimeTable { get; set; }
    }
}
