//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW10_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPhoto
    {
        public int IDUser { get; set; }
        public string PhotoPath { get; set; }
        public byte[] PhotoBinary { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
